CAN_ID_KEY = "CAN_ID"
PERIOD_KEY = "period"

THROTTLE_KEY = "throttle"
BRAKE_KEY = "brake"
STEER_KEY = "steer"
REVERSE_KEY = "reverse"
HAND_BRAKE_KEY = "hand_brake"
AUTOPILOT_KEY = "autopilot"
MANUAL_TRANSMISSION_KEY = "manual_transmission"
GEAR_KEY = "gear"
LIGHT_TYPE_KEY = "ligh_type"
HIGH_BEAM_KEY = "high_beam"
BLINKER_KEY = "blinker"
INTERIOR_LIGHT_KEY = "interior_light"
DOORS_KEY = "doors"
